import random

class FGenerator:
    def __init__(self):
        self.reviews: list = [
            "I've bought several accounts from this shop and they've all worked perfectly. Highly recommended!",
            "The prices are really reasonable and the accounts work perfectly. Will definitely be buying from here again!",
            "I was a bit hesitant to buy from here at first, but I'm so glad I did! The account worked perfectly and the customer service was great.",
            "I've had bad experiences with other account shops in the past, but this one exceeded my expectations. The account worked perfectly and the transaction was quick and easy.",
            "I had an issue with my account and the customer service team was able to help me resolve it quickly. Great service!",
            "This is hands down the best Minecraft account shop out there. The prices are great and the accounts work perfectly.",
            "I was worried about buying a Minecraft account online, but this shop made the process quick and easy. The account worked perfectly and the customer service was great.",
            "I've been a customer of this shop for a while now and I've never been disappointed. The accounts always work perfectly and the prices are great.",
            "I was a bit skeptical about the prices being so low, but I decided to give it a try and I'm so glad I did. The account worked perfectly and the transaction was quick and easy.",
            "I've recommended this shop to all of my friends who play Minecraft. The accounts are great quality and the prices are unbeatable.",
            "This shop is amazing! I got a premium account for a fraction of the usual price.",    
            "The accounts I got from this shop were all working and had no issues.",    
            "Fast delivery and great customer service. Highly recommended!",    
            "I was skeptical at first, but I decided to give this shop a chance and I'm glad I did.",    
            "Best Minecraft account shop I've ever used. Will definitely be back for more!",    
            "Excellent selection of accounts and prices that can't be beat.",    
            "I've tried other Minecraft account shops before, but this one is by far the best.",    
            "I had a question about my account and the customer service team was quick to respond and help me out.",    
            "If you're looking for a reliable and affordable Minecraft account, this is the place to go.",    
            "I've purchased multiple accounts from this shop and have never had any problems. Highly recommend!"
            "I've bought multiple accounts from this shop and they always deliver quickly and have great customer service.",
            "The accounts I've purchased here have all worked perfectly, no issues whatsoever.",
            "The prices are really reasonable for the quality of the accounts you get, I highly recommend this shop.",
            "I was a bit skeptical at first, but I decided to give this shop a chance and I'm glad I did. The account works perfectly.",
            "The transaction was quick and easy, and the account works perfectly. I'm very satisfied with my purchase.",
            "The customer service is fantastic, they were very helpful and responsive when I had a question about my account.",
            "I've bought several accounts from this shop and have never had any issues. Highly recommend!",
            "I was a bit nervous about buying an account online, but this shop made the process so easy and stress-free.",
            "The accounts are exactly as described, no issues whatsoever. This is my go-to shop for Minecraft accounts.",
            "The prices are very competitive and the accounts work perfectly. I wouldn't buy from any other shop!",
            "I've purchased accounts from other shops before and have always been disappointed, but this shop exceeded my expectations.",
            "I had a question about my account and the customer service was quick to respond and very helpful. Highly recommend!",
            "The account was delivered quickly and works perfectly. I'll definitely be buying from this shop again.",
            "I've recommended this shop to all my friends who play Minecraft. The accounts are top-notch and the prices are unbeatable.",
            "I was a bit hesitant to buy an account online, but this shop made the process so easy and stress-free. Highly recommend!",
            "I've purchased multiple accounts from this shop and have never had any issues. The accounts work perfectly and the prices are great.",
            "The customer service is fantastic, they always respond quickly and are very helpful. I'll definitely be a repeat customer!",
            "I've tried other Minecraft account shops before, but this one is by far the best. The accounts work perfectly and the prices are unbeatable.",
            "I had an issue with my account and the customer service was quick to resolve it. I'll definitely be buying from this shop again!",
            "The account was delivered quickly and works perfectly. I'm very happy with my purchase.",
            "I've purchased accounts from several different shops before, but this one is my favorite. The accounts work perfectly and the prices are great.",
            "The customer service is top-notch, they're always quick to respond and very helpful. Highly recommend!",
            "I was a bit hesitant to buy an account online, but this shop made the process so easy and stress-free. The account works perfectly.",
            "I've purchased multiple accounts from this shop and have always been satisfied. Highly recommend!",
            "The prices are very reasonable and the accounts work perfectly. I wouldn't buy from any other shop!",
            "The customer service is fantastic, they always respond quickly and are very helpful. This is my go-to shop for Minecraft accounts.",
            "I was a bit skeptical at first, but I decided to give this shop a chance and I'm glad I did. The account works perfectly.",
            "I've bought several accounts from this shop and have never had any issues. Highly recommend!",
            "The account was delivered quickly and works perfectly. I'm very happy with my purchase.",
            "I had an issue with my account and the customer service was quick to resolve it. I'll definitely be buying from this shop again!",
            "The prices are very competitive and the accounts work perfectly. I wouldn't buy from any other shop",
            "The customer service here is amazing. They were able to help me with an issue I had in no time at all.",
            "I've bought several accounts from this shop and I've never been disappointed. They always deliver quickly and the accounts are top-notch.",
            "I would definitely recommend this shop to anyone looking for a reliable place to buy Minecraft accounts.",
            "I was a bit skeptical at first, but after buying an account from this shop I can say that they're the real deal.",
            "I had a small issue with my purchase, but the support team at this shop was quick to help me resolve it. Great service!",
            "If you're looking for a trustworthy place to buy Minecraft accounts, look no further. This shop is the best!",
            "I've tried a few other shops in the past, but this one is by far the best. The accounts are high quality and the prices are great.",
            "I was a bit worried about buying an account online, but this shop made the process so easy. I got my account right away and it's been working great.",
            "I've been a customer of this shop for a while now and I've never had any issues. They're always reliable and their accounts are top-notch.",
            "This is the only shop I'll buy Minecraft accounts from. The prices are fair and the quality is always great.",
            "I couldn't be happier with my purchase from this shop! The account was exactly as described and the delivery was lightning fast. Thanks so much!",
            "Great shop! The customer service was top-notch and the account was delivered very quickly. Highly recommend.",
            "I was hesitant to buy a Minecraft account online, but this shop made the process easy and the account works perfectly. Thanks!",
            "Excellent seller! The account was delivered instantly and works great. Will definitely be buying from this shop again.",
            "I've purchased accounts from other shops before, but this one is by far the best. The prices are reasonable and the customer service is excellent.",
            "I received my account within minutes of placing my order. The shop owner was very friendly and helpful. Would definitely recommend!",
            "My son loves his new Minecraft account. Thank you for providing a safe and secure way to purchase accounts online.",
            "I've bought several accounts from this shop and have never had any issues. Highly recommend to anyone looking for a reliable seller.",
            "The account I received from this shop was even better than I expected. The price was great and the delivery was super fast.",
            "I had some questions about the account before purchasing and the shop owner was very helpful and responsive. The account works perfectly!",
            "I've been playing Minecraft for years and have purchased accounts from several different shops. This one is by far the best. Highly recommend!",
            "I needed a new Minecraft account quickly and this shop delivered. The account was easy to set up and works perfectly. Thanks!",
            "I was a little nervous about buying a Minecraft account online, but this shop made the process easy and stress-free. Highly recommend!",
            "I've purchased multiple accounts from this shop and have never been disappointed. The customer service is excellent and the accounts work perfectly.",
            "I received my account within minutes of placing my order. The shop owner was very friendly and helpful. Would definitely recommend!",
            "I needed a new Minecraft account for my son and this shop delivered. The account was easy to set up and works perfectly. Thanks!",
            "I had some questions about the account before purchasing and the shop owner was very helpful and responsive. The account works perfectly!",
            "Great shop! The customer service was top-notch and the account was delivered very quickly. Highly recommend.",
            "I received my account within minutes of placing my order. The shop owner was very friendly and helpful. Would definitely recommend!",
            "The account I received from this shop was even better than I expected. The price was great and the delivery was super fast.",
            "I've purchased accounts from other shops before, but this one is by far the best. The prices are reasonable and the customer service is excellent.",
            "I was hesitant to buy a Minecraft account online, but this shop made the process easy and the account works perfectly. Thanks!",
            "Excellent seller! The account was delivered instantly and works great. Will definitely be buying from this shop again.",
            "I've bought several accounts from this shop and have never had any issues. Highly recommend to anyone looking for a reliable seller.",
            "I've been playing Minecraft for years and have purchased accounts from several different shops. This one is by far the best. Highly recommend!",
            "My son loves his new Minecraft account. Thank you for providing a safe and secure way to purchase accounts online.",
            "I received my account within minutes of placing my order. The shop owner was very friendly and helpful. Would definitely recommend!",
            "I had some questions about the account before purchasing and the shop owner was very helpful and responsive. The account works perfectly",]
        
    def generate_feedback(self):
        return random.choice(self.reviews)
